
# ä½œè€…ä¿¡æ¯
boy:
  name: ç”· #ç”·ç”Ÿæ˜µç§°
  avatar: 
girl:
  name: å¥³ #å¥³ç”Ÿæ˜µç§°
  avatar: 

#å¯¼èˆªæ¡
menu:
  ğŸš©é»‘çŸ³åšå®¢: http://hm46334.hanming.fun
  ğŸ’æƒ…ä¾£å“”å“”: http://hm46334.hanming.fun/lovebb/
  #é¡µé¢åç§°: é¡µé¢åœ°å€



# å“”å“”è®¾ç½® â˜†å¿…é¡»
#ç”·ç”Ÿçš„å“”å“”
boybb:
  appId: 1
  appKey: 1
  serverUrl: https://bbapi.heson10.com

#å¥³ç”Ÿçš„å“”å“”
girlbb:
  appId: 1
  appKey: 1
  serverUrl: https://xfbb.heson10.com


# ç›¸æ‹çºªå¿µæ—¥
anniversary: '2015-06-30'

# ç™¾åº¦ç»Ÿè®¡
baidu_analytics_key: # 5fb5fd0062e816d3a3ca2dacf095bc0f 